event_manager/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

import authentication.views
import events.views

urlpatterns = [
    path('admin/', admin.site.urls),
    # urls pour authentification
    path('connexion/', LoginView.as_view(
        template_name='authentication/login.html',
        redirect_authenticated_user=True
    ), name='login'),
    path('deconnexion/', authentication.views.logout_user, name='logout'),
    path('inscription/', authentication.views.signup_page, name='signup'),
     path('users/', authentication.views.user_list, name='user_list'),
    # urls pour les évènements
    path('', events.views.event_list, name='home'),
    path('events/', events.views.event_list, name='event_list'),
    path('events/<int:event_id>/', events.views.event_detail, name='event_detail'),
    path('events/<int:event_id>/register/', events.views.register_event, name='register_event'),
    path('events/new/', events.views.add_event, name='add_event'),
]


# Uniquement si on est en mode développement (pour le téversement des photos)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentication/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from PIL import Image


class User(AbstractUser):
    profile_photo = models.ImageField(upload_to='profile_photos/', verbose_name='Photo de profil', null=True, blank=True)
    
    IMAGE_MAX_SIZE = (800, 800)
    
    def resize_image(self):
        if self.profile_photo:
            image = Image.open(self.profile_photo)
            image.thumbnail(self.IMAGE_MAX_SIZE)
            image.save(self.profile_photo.path)
        
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.resize_image()

events/models.py
from django.db import models
#from authentication.models import User
from django.conf import settings


class Event(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    date = models.DateTimeField()
    #organizer = models.ForeignKey(User, on_delete=models.CASCADE, related_name='events')
    organizer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='events')

    def __str__(self):
        return self.title
    

class Registration(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    #user = models.ForeignKey(User, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user.username} - {self.event.title}'

authentication/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class LoginForm(forms.Form):
    username = forms.CharField(max_length=63, label='Nom d\'utilisateur')
    password = forms.CharField(max_length=63, widget=forms.PasswordInput, label='Mot de passe')
    
   
class SignupForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = ('username', 'email', 'first_name', 'last_name', 'profile_photo')

events/forms.py
from django import forms
from .models import Event, Registration

class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        #fields = ['title', 'description', 'date', 'organizer']
        fields = ['title', 'description', 'date']
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'})
        }

class RegistrationForm(forms.ModelForm):
    class Meta:
        model = Registration
        fields = []

authentication/views.py
from django.contrib.auth import login, logout
from django.shortcuts import render, redirect
from django.conf import settings
from django.contrib.auth.decorators import login_required

from authentication.forms import SignupForm
from authentication.models import User


def logout_user(request):
    logout(request)
    return redirect('login')

def signup_page(request):
    if request.method == 'POST':
        form = SignupForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect(settings.LOGIN_REDIRECT_URL)
    else:
        form = SignupForm()
    
    return render(request, 'authentication/signup.html', context={'form': form})

def user_list(request):
    users = User.objects.all()
    return render(request, 'authentication/user_list.html', {'users': users})

events/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.conf import settings
from django.db.models import Q, Count

from .models import Event, Registration
from .forms import EventForm, RegistrationForm


@login_required
def home(request):
    return render(request, 'events/home.html')

@login_required
def add_event(request):
    if request.method == 'POST':
        form = EventForm(request.POST)
        if form.is_valid():
            event = form.save(commit=False)
            event.organizer = request.user
            event.save()
            return redirect('event_list')
    else:
        form = EventForm()
    return render(request, 'events/event_new.html', {'form': form})

@login_required
def event_list(request):
    query = request.GET.get('q')
    if query:
        events = Event.objects.filter(
            Q(title__icontains=query) |
            Q(description__icontains=query) |
            Q(date__icontains=query)
        ).annotate(num_registrations=Count('registration'))
    else:
        #events = Event.objects.all()
        events = Event.objects.all().annotate(num_registrations=Count('registration'))
    return render(request, 'events/event_list.html', {'events': events})

#def event_list(request):
#    events = Event.objects.annotate(num_registrations=Count('registration'))
#    return render(request, 'events/event_list.html', {'events': events})

@login_required
def event_detail(request, event_id):
    event = get_object_or_404(Event, id=event_id)
    registrations = Registration.objects.filter(event=event)
    
    user_is_registered = False
    if request.user.is_authenticated:
        user_is_registered = Registration.objects.filter(event=event, user=request.user).exists()
        
        context = {
            'event': event, 
            'registrations': registrations,
            'user_is_registered': user_is_registered,
        }
    return render(request, 'events/event_detail.html', context=context)

@login_required
def register_event(request, event_id):
    event = get_object_or_404(Event, id=event_id)
    
    user_is_registered = False
    if request.user.is_authenticated:
        user_is_registered = Registration.objects.filter(event=event, user=request.user).exists()
        
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            registration = form.save(commit=False)
            registration.event = event
            registration.user = request.user
            registration.save()
            send_mail(
                'Confirmation d\'inscription',
                f'Vous êtes inscrit à l\'événement : {event.title}',
                settings.DEFAULT_FROM_EMAIL,
                [request.user.email],
            )
            return redirect('event_detail', event_id=event.id)
    else:
        form = RegistrationForm()
        
    return render(request, 'events/register_event.html', {'form': form, 'event': event, 'user_is_registered': user_is_registered})

authentication/templates/authentication/login.html
{% extends 'base.html' %}
{% load custom_filters %}

{% block content %}
    <div class="container" style="width:450px;">
        <p class="mt-5">{{ message }}</p>
        <div class="card shadow px-4 py-2 mt-3">
            <h4 class="text-center">Connexion</h4>
            <form method="post" class="mt-3">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="id_username" class="form-label">Nom d'utilisateur</label>
                    {{ form.username | add_class:"form-control" }}
                </div>
                <div class="mb-3">
                    <label for="id_password" class="form-label">Mot de passe</label>
                    {{ form.password | add_class:"form-control" }}
                </div>
                <button type="submit" class="btn btn-primary">Se connecter</button>
            </form>
            <p>Pas encore membre ? <a href="{% url 'signup' %}">Inscrivez-vous maintenant !</a></p>
        </div>
    </div>
{% endblock content %}

authentication/templates/authentication/signup.html
{% extends 'base.html' %}
{% load custom_filters %}

{% block content %}
    <div class="container card shadow px-4 py-2 mt-5">
        {% if form.errors %}
            <div class="alert alert-danger" role="alert">
                <strong>Erreur !</strong> Veuillez corriger les erreurs suivantes :
                <ul>
                    {% for field, errors in form.errors.items %}
                        {% for error in errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    {% endfor %}
                </ul>
            </div>
        {% endif %}

        <form method="post" enctype="multipart/form-data" class="mt-3">
            {% csrf_token %}
            <div class="mb-3">
                <label for="id_username" class="form-label">Nom d'utilisateur</label>
                {{ form.username | add_class:"form-control" }}
            </div>
            <div class="mb-3">
                <label for="id_email" class="form-label">Adresse email</label>
                {{ form.email | add_class:"form-control" }}
            </div>
            <div class="row">
                <div class="col">
                    <div class="mb-3">
                        <label for="id_first_name" class="form-label">Prénom</label>
                        {{ form.first_name | add_class:"form-control" }}
                    </div>
                </div>
                <div class="col">
                    <div class="mb-3">
                        <label for="id_last_name" class="form-label">Nom de famille</label>
                        {{ form.last_name | add_class:"form-control" }}
                    </div>
                </div>
            </div>
            <div class="mb-3">
                <label for="id_profile_photo" class="form-label">Photo de profil</label>
                {{ form.profile_photo | add_class:"form-control" }}
            </div>
            <div class="mb-3">
                <label for="id_password1" class="form-label">Mot de passe</label>
                {{ form.password1 | add_class:"form-control" }}
            </div>
            <div class="mb-3">
                <label for="id_password2" class="form-label">Confirmer le mot de passe</label>
                {{ form.password2 | add_class:"form-control" }}
            </div>
            <button type="submit" class="btn btn-primary">S'inscrire</button>
        </form>
    </div>
{% endblock content %}

authentication/templates/authentication/user_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <h2 class="my-4">Liste des utilisateurs</h2>
    <div class="card shadow px-4 py-2">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Photo</th>
                    <th>Nom utilisateur</th>
                    <th>Prénom</th>
                    <th>Nom de famille</th>
                    <th>Email</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for user in users %}
                    <tr>
                        <td>
                            {% if user.profile_photo %}
                                <img class="avatar img-thumbnail rounded-circle" src="{{ user.profile_photo.url }}" width="60px" height="60px">
                            {% else %}
                                <img class="avatar img-thumbnail rounded-circle" src="{% static 'images/default_profile.png' %}" width="60px" height="60px">
                            {% endif %}
                        </td>
                        <td class="align-middle">
                            <span class="bg-success text-light rounded px-2 py-1"><i>{{ user.username }}</i></span>
                        </td>
                        <td class="align-middle">{{ user.first_name }}</td>
                        <td class="align-middle">{{ user.last_name }}</td>
                        <td class="align-middle">
                            <span class="bg-dark text-light rounded px-2 py-1">{{ user.email }}</span>
                        </td>
                        <td class="align-middle">
                            <a href="#">modifier</a>
                            <a href="#">supprimer</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

events/templates/events/event_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h2 class="my-4">{{ event.title }}</h2>
    <div class="card shadow px-4 py-2">
        <p><i>{{ event.description }}</i></p>
        <p><strong>Organisateur </strong> : {{ event.organizer.username }}</p>
        <p><strong>Date </strong> : {{ event.date }}</p>
        
        {% if user_is_registered %}
            <p class="bg-success text-light px-3 py-2 rounded">Tu es déjà inscrit</p>
        {% else %}
            <a href="{% url 'register_event' event.id %}">S'inscrire</a>
        {% endif %}
    </div>
    <h2 class="my-4">Liste des inscrits à cet évènement</h2>
    <ul>
        {% for registration in registrations %}
            <li><strong>{{ registration.user.username }}</strong> <i>(inscrit le {{ registration.timestamp }})</i></li>
        {% empty %}
            <li>Pas encore d'inscrits</li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

events/templates/events/event_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h2 class="my-4">Liste des événements</h2>
    <form method="get">
        <div class="row">
            <div class="col-8">
                <input type="text" name="q" placeholder="Rechercher..." class="form-control">
            </div>
            <div class="col-4">
                <button type="submit" class="btn btn-primary">Rechercher</button>
            </div>
        </div>
    </form>
    
    <div class="card shadow my-4 p-4">
        <ul class="list-group">
            {% for event in events %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <a href="{% url 'event_detail' event.id %}">{{ event.title }}</a> - {{ event.date }}
                    <span class="badge bg-primary rounded-pill">{{ event.num_registrations }}</span>
                </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

events/templates/events/event_new.html
{% extends 'base.html' %}
{% load custom_filters %}

{% block content %}
<div class="container">
    <h2 class="my-4">Ajout de nouvel évènement</h2>
    <div class="card shadow px-4 py-2">
        <form method="post">
            {% csrf_token %}
            <div class="mb-3">
                <label for="id_title" class="form-label">Titre</label>
                {{ form.title | add_class:"form-control" }}
            </div>
            <div class="mb-3">
                <label for="id_description" class="form-label">Description</label>
                {{ form.description | add_class:"form-control" }}
            </div>
            <div class="mb-3">
                <label for="id_date" class="form-label">Date</label>
                {{ form.date | add_class:"form-control" }}
            </div>
            <button type="submit" class="btn btn-primary">Ajouter</button>
        </form>
    </div>
</div>
{% endblock %}

events/templates/events/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container">
        <h1>Gestion Evènements</h1>
    </div>

{% endblock content %}

events/templates/events/register_event.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h2 class="my-4">S'inscrire à l'événement : {{ event.title }}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}

        {% if user_is_registered %}
        <button type="submit" class="btn btn-primary" disabled>S'inscrire</button>
        {% else %}
        <button type="submit" class="btn btn-primary">S'inscrire</button>
        {% endif %}
    </form>
</div>
{% endblock %}

templates/base.html
{% load static %}
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}Gestion - Evènements{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'style.css' %}">
        <link rel="stylesheet" href="{% static 'bootstrap-5.2.3/dist/css/bootstrap.min.css' %}">
        {% block stylesheet %}
            <!-- Inclure les liens vers les feuilles de style CSS ici -->
        {% endblock %}
    </head>
    <body>
        {% include 'partials/navbar.html' %}
        
        {% block content %}{% endblock content %}

        {# include 'partials/footer.html' #}

        <script src="{% static 'jquery-3.7.0.min.js' %}"></script>
        <script src="{% static 'bootstrap-5.2.3/dist/js/bootstrap.bundle.min.js' %}"></script>
        {% block javascript %}
            <!-- Inclure les scripts JavaScript ici -->
        {% endblock %}
    </body>
</html>

templates/partials/footer.html
<!-- Section Contact (Footer) -->
<footer id="contact" class="bg-light py-2 px-4" >
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-4">
                <h2>Contactez-nous</h2>
                <p>Si vous avez des questions ou des commentaires, n'hésitez pas à nous contacter :</p>
                <ul>
                    <li>Email: info@mairie-ouani.com</li>
                    <li>Téléphone: +269 394 04 59</li>
                    <!-- Ajoutez d'autres informations de contact ici -->
                </ul>
            </div>
            <div class="col-sm-12 col-md-4">
                <!-- Ajoutez ici un formulaire de contact -->
                <form action="#" method="post">
                    {% csrf_token %}
                    <!-- Ajoutez les champs du formulaire ici -->
                    <label for="message_contact" class="control-label">Message</label>
                    <input type="text" id="message_contact" class="form-control">
                    <button type="submit" class="btn btn-primary mt-2">Envoyer</button>
                </form>
            </div>
            <div class="col-sm-12 col-md-4">
                <!-- Ajoutez ici des liens vers les pages d'inscription et de connexion -->
                <a href="#">S'inscrire</a>
                <a href="#">Se connecter</a>
            </div>
        </div>
    </div>
</footer>

templates/partials/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'home' %}">TODOLIST</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'event_list' %}">Evènements</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'add_event' %}">Nouvel Evènement</a>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'user_list' %}">Utilisateurs</a>
            </li>
          </li>
          {%  if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}">Déconnexion</a>
            </li>  
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'signup' %}">Inscription</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">Connexion</a>
            </li>
          {% endif %}

          {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link bg-success text-light rounded px-3 py-2">{{ user.username }}</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
</nav>